version: '3.7'

services:
  web:
    container_name: webapp
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'mysql_pwd'
    ports:
      - "3306:3306"
    volumes:
      - web_data:/var/lib/mysql

volumes:
  web_data:
    name: spring_security_db
